
import type { User as SupabaseUser } from '@supabase/supabase-js';

export interface AIAssistant {
  id: string; // UUID from Supabase
  name: string;
  tagline: string;
  description: string;
  category: string;
  price: string;
  imageUrl: string; // Corresponds to 'image_url' in Supabase; mapped in service layer
  features: string[];
  systemPrompt: string; // Corresponds to 'system_prompt' in Supabase; mapped in service layer
  accentColor: string; // Corresponds to 'accent_color' in Supabase; mapped in service layer
  created_at?: string; // ISO date string from Supabase, auto-generated
  // user_id?: string; // Optional: To link assistant to a user. Would require schema change.
}

// For creating new assistants, id and created_at are auto-generated by Supabase
export type NewAIAssistant = Omit<AIAssistant, 'id' | 'created_at' | 'user_id'>;


export interface ChatMessage {
  id: string;
  sender: 'user' | 'ai';
  text: string;
  timestamp: number;
}

// Re-export SupabaseUser for use in the app
export type User = SupabaseUser;
